export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_ERROR: "PROFILE_DATA_FETCH_ERROR",
    DATA_EDITED: "PROFILE_DATA_EDITED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
  },
  post: {
    POSTS_FETCHING: "POSTS_FETCHING",
    POSTS_FETCHED: "POSTS_FETCHED",
    POST_FETCH_ERROR: "POST_FETCH_ERROR",
    POST_CREATED: "POST_CREATED",
    POST_EDITED: "POST_EDITED",
    POST_DELETED: "POST_DELETED",
  },
};
